#!/bin/bash

echo -e "Compute mean\n"

echo -e "confused\n"
python computeMeans.py confused_large_filter_difference_with_real_value.txt means/confused_large_filter_difference_with_real_value.txt
python computeMeans.py confused_large_filter_pacman_belief_state_summary.txt means/confused_large_filter_pacman_belief_state_summary.txt
python computeMeans.py confused_large_filter_walls_difference_with_real_value.txt means/confused_large_filter_walls_difference_with_real_value.txt
python computeMeans.py confused_large_filter_walls_pacman_belief_state_summary.txt means/confused_large_filter_walls_pacman_belief_state_summary.txt

echo -e "afraid\n"
python computeMeans.py afraid_large_filter_difference_with_real_value.txt means/afraid_large_filter_difference_with_real_value.txt
python computeMeans.py afraid_large_filter_pacman_belief_state_summary.txt means/afraid_large_filter_pacman_belief_state_summary.txt
python computeMeans.py afraid_large_filter_walls_difference_with_real_value.txt means/afraid_large_filter_walls_difference_with_real_value.txt
python computeMeans.py afraid_large_filter_walls_pacman_belief_state_summary.txt means/afraid_large_filter_walls_pacman_belief_state_summary.txt

echo -e "scared\n"
python computeMeans.py scared_large_filter_difference_with_real_value.txt means/scared_large_filter_difference_with_real_value.txt
python computeMeans.py scared_large_filter_pacman_belief_state_summary.txt means/scared_large_filter_pacman_belief_state_summary.txt
python computeMeans.py scared_large_filter_walls_difference_with_real_value.txt means/scared_large_filter_walls_difference_with_real_value.txt
python computeMeans.py scared_large_filter_walls_pacman_belief_state_summary.txt means/scared_large_filter_walls_pacman_belief_state_summary.txt
